### ISSUE TITLE
Stop jgit from breaking configuration cache

### ISSUE THREAD

**Issue by shysteph** [nebula-plugins/gradle-info-plugin#104]
The gradle configuration cache can't work with anything that executes a seperate executable. Jgit for getting the system config does this. It seems silly for a "pure java" implementation but whatever.  The GIT_CONFIG_NOSYSTEM environment variable turns off this behavior so it needs to be set before doing anything that would pull the system config and restored afterwards. There may be a better and cleaner way of doing this but I couldn't figure out how.
PR #103

**Comment by rpalcolea** [comment]
Hi!

Thanks for bringing this up

We just released 12.1.0 with a change to stop using `jgit` and rely on native git calls using `providers.exec`.

We thought it would be better to just get rid of jgit as the operations aren't complex 

Can you give it a try and let us know how it goes?

**Comment by shysteph** [comment]
Your changes seem to have fixed it.  Now I have the same problem with nebula release through grgit.  Maybe ill try porting over your changes to there as well.
