### ISSUE TITLE
Upgrade to latest release of p4java

### ISSUE THREAD

**Issue by elygre** [nebula-plugins/gradle-info-plugin#15]
The gradle-info-plugin currently uses p4java version 2011.1.297684 (com.perforce:p4java-jfrog:2011.1.297684), which requires com.jcraft:jzlib:1.0.7.

This version of jzlib conflicts with jRuby, which in turns is used by asciidoctor, and which ultimately means that there are problems using both the info plugin and asciidoctor-pdf in the same gradle build. See https://github.com/elygre/asciidoctor-pdf-final-class and http://discuss.asciidoctor.org/Using-asciidoctorj-pdf-from-gradle-tp2731p2986.html for more information on the conflict.

This issue is a request to upgrade to the latest release of p4java 2014.1.965322, ref https://bintray.com/bintray/jcenter/com.perforce%3Ap4java/2014.1.965322/view. This version also fixes the INDEX.LIST-issue that forced the use of a third party packaging of p4java, ref https://github.com/nebula-plugins/gradle-info-plugin/blob/gradle-2.2/build.gradle#L19-L24.

I do not have access to a perforce repository anywhere, so I am unable to properly test and verify this change. However, the following change in build.gradle builds successfully:

    -    compile 'com.perforce:p4java-jfrog:2011.1.297684'
    +    compile 'com.perforce:p4java:2014.1.965322'

**Comment by bmuschko** [comment]
Would you be interested in providing a pull request for this? Generally speaking, you can avoid the conflict by simply excluding the P4Java library when declaring the plugin in the `buildscript` block.

**Comment by elygre** [comment]
I have created a pull request that compiles and builds, including running unit tests. As I do not have access to a perforce repository, I do not know if there are any hidden problems lurking, though.

**Comment by elygre** [comment]
(Oh, and yes: Using the `buildscript` block with exclusions works for me. I kinda forgot all about it when the new `plugins` section syntax arrived!)
