### ISSUE TITLE
BasicInfoPlugin interferes with Gradle build caching by adding timestamp

### ISSUE THREAD

**Issue by sergeykad** [nebula-plugins/gradle-info-plugin#50]
Basically, timestamp makes every build result unique and prevents using cached results of tests execution.
In other words, if the plugin and build cache are enabled, executing `gradlew clean build` repeatedly will run unit tests everytime, while without BasicInfoPlugin tests results are taken from build cache.
Can configuration be added to the plugin to toggle individual properties off or at least the timestamp?

**Comment by sergeykad** [comment]
That's exactly what I was looking for. 
Thanks.

**Comment by rpalcolea** [comment]
no problem, if that works... feel free to close the issue 👍
