### ISSUE TITLE
error using nebula.plugin.info.InfoPlugin with Gradle 6.0+ versions

### ISSUE THREAD

**Issue by ramakrishnakaushik97** [nebula-plugins/gradle-info-plugin#71]
While using '**com.netflix.nebula:gradle-info-plugin:7.1.4+**' version ..compiling with **Gradle 6.0+ version** , I am getting below error.
org.gradle.api.provider.ProviderFactory.systemProperty(Ljava/lang/String;)Lorg/gradle/api/provider/Provider;

Please suggest.

**Comment by DanielThomas** [comment]
That's looks like info 8.+ - you might be getting upgraded via conflict resolution. Check `buildEnvironment` and make sure you're at least Gradle 6.1 if you're picking up 8.0.0 and later or downgrade.

**Comment by DanielThomas** [comment]
See https://github.com/nebula-plugins/gradle-info-plugin/releases

**Comment by ramakrishnakaushik97** [comment]
@DanielThomas 

I am using below nebula dependency versions with Gradle 6.1 version, Still I am getting the same issue.

	compile "com.netflix.nebula:gradle-info-plugin:8.0.0"
	compile "com.netflix.nebula:nebula-release-plugin:14.0.5"
	compile "com.netflix.nebula:gradle-metrics-plugin:10.0.1"
	compile "com.netflix.nebula:gradle-lint-plugin:16.9.0"
	compile "com.netflix.nebula:nebula-publishing-plugin:17.0.0"

**Comment by ramakrishnakaushik97** [comment]
@DanielThomas 
I have individually checked on each of the above plugin. Only gradle-info-plugin has the compatibility issue.  I have tried using v7.1.+ version till latest release v8.3.0 with Gradle 6.x. It does not work.

Error
> org.gradle.api.provider.Provider.forUseAtConfigurationTime()Lorg/gradle/api/provider/Provider;

**Comment by rpalcolea** [comment]
Hi,

Just checked this and you are right

8.x requires gradle 6.5 as it uses a new API https://docs.gradle.org/current/javadoc/org/gradle/api/provider/Provider.html#forUseAtConfigurationTime--

I updated the release notes to reflect this
